from app import app
from models import db, Ocean, Animal, User, Favorite # models go here
from faker import Faker

faker = Faker()

if __name__ == '__main__':
    with app.app_context():

        Ocean.query.delete()
        Animal.query.delete()
        User.query.delete()
        
        print("Seeding database...")

        ocean1 = Ocean(name='Atlantic', avg_depth='10,932 ft', deepest_point='28,232 ft', surface_area='41.1 million mi²', about='The Atlantic Ocean is approximately one-fifth of Earth\'s surface and separating the continents of Europe and Africa to the east from those of North and South America to the west. The ocean\'s name, derived from Greek mythology, means the “Sea of Atlas.” It is second in size to the Pacific Ocean.',
        ofun_fact='The Atlantic Ocean is the youngest of the five oceans, having formed during the Jurassic Period approximately 150 million years ago following the breakup of the supercontinent Pangaea.',
        img='https://csridentity.com/images/atlanticocean.jpg', map='https://science4fun.info/wp-content/uploads/2022/02/Atlantic-Ocean-Map.jpg' )
        ocean2 = Ocean(name='Pacific', avg_depth='13,000 ft', deepest_point='35,876 ft', surface_area='63.8 million mi²', about='The Pacific Ocean is the largest and deepest ocean on Earth. It spans 60 million square miles from California to China, and in certain regions extends tens of thousands of feet below the surface of the water. It\'s name stands for peaceful.',
        ofun_fact='A fun fact about the Pacific Ocean is that it is the largest ocean on Earth, covering more area than all the land on Earth combined (More then 30 percent of Earth\'s surface area), and also holds the deepest point on the planet, known as the Challenger Deep in the Mariana Trench',
        img='https://www.americanoceans.org/wp-content/uploads/2023/09/atlantic-vs-pacific-ocean-scaled.jpeg', map='https://science4fun.info/wp-content/uploads/2022/02/Pacific-Ocean-Map.jpg' )
        ocean3 = Ocean(name='Indian', avg_depth='12,274 ft', deepest_point='23,920 ft', surface_area='27.24 million mi²', about='The Indian Ocean is the third-largest of the world\'s five oceanic divisions, covering 20 percent of the water on Earth\'s surface. It is bounded by Asia to the north, Africa to the west and Australia to the east. To the south it is bounded by the Southern Ocean, or Antarctica. It is named after India',
        ofun_fact='A fun fact about the Indian Ocean is that it contains a massive underwater plateau called the Kerguelen Plateau, which is considered a "submerged continent" and is roughly three times the size of Japan; making it one of only two major submerged continents on Earth',
        img='https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/21/2020/10/how-to-sail-across-the-indian-ocean-Le-Morne-Brabant-peninsula-maritius-credit-Roberto-Moiola-Getty.jpg', map='https://www.arcgis.com/sharing/rest/content/items/147937cf124843fcb86126b028e8d97c/resources/images/widget_954/1684939456673.png' )
        ocean4 = Ocean(name='Artic', avg_depth='3,240 ft', deepest_point='17,880 ft', surface_area='5.427 million mi²', about='The Arctic Ocean is the smallest and shallowest of the world\'s five oceanic divisions. It is the coldest of the world\'s oceans. The International Hydrographic Organization recognizes it as an ocean, although some oceanographers call it the Arctic Mediterranean Sea. The word "arctic" comes from the Greek word arktikos, which means "near the bear".',
        ofun_fact='The Arctic Ocean is mostly frozen over for most of the year, but the ice cover is shrinking due to climate change.',
        img='https://cff2.earth.com/uploads/2021/02/05165228/shutterstock_780681282-scaled.jpg', map='https://nsidc.org/sites/default/files/styles/article_image/public/images/Map/ArcticOcean.png.webp?itok=RRcf2eUu' )
        ocean5 = Ocean(name='Southern/Antarctic', avg_depth='10,728 ft', deepest_point='24,390 ft', surface_area='7.849 million mi²', about='The Southern Ocean (also known as the Antarctic Ocean) is the most southerly of the planet\'s five oceans. It completely surrounds the continent of Antarctica and connects the southern waters of the Pacific, Indian, and Atlantic oceans. The Southern Ocean is the fourth-largest ocean in the world. The name "Antarctica" comes from the Greek word antarktikos, which means "opposite to the Arctic" or "opposite to the north"',
        ofun_fact='The Antarctic Ocean has the strongest average winds on Earth, especially in the latitudes known as the "Roaring Forties", "Furious Fifties", and "Shrieking Sixties". Also, the ocean floor has not been explored here.',
        img='https://e360.yale.edu/assets/site/_1500x1500_fit_center-center_80/Antarctic-Waters.jpg', map='https://www.blue-growth.org/Oceans_Rivers_Seas/Seas_Pictures_Oceans_Rivers/Antarctica-RegionSouthern-Ocean-Convergence.gif' )


        animal1 = Animal(name='Atlantic Blue Marlin', scientific_name = 'Makaira nigricans', lifespan='F: 27 years, M: 18 years', about='Atlantic blue marlins can grow to be 14 feet long and weigh 2000 pounds. Females grow far larger than males. They don\'t form a bill until they are older.', fun_fact = 'Blue marlin are among the fastest fish in the ocean and use their spear-shaped upper jaws to slash through schools of prey.', food = 'Atlantic blue marlin prey on squid and epipelagic fishes such as: Mackerel, Tuna, Dolphinfishes', ocean = ocean1, img= 'https://fishflags.com/cdn/shop/articles/blue.marlin.enio.morales_1100x.jpg?v=1589410327' )
        animal2 = Animal(name='Pacific White Sided Dolpin', scientific_name = 'Lagenorhynchus obliquidens', lifespan='More than 40 years', about='As medium-sized dolphins, these animals can reach up to 400 pounds and 8 feet in length, with males typically being larger than females. Pacific white-sided dolphins are gregarious and often found in large groups of tens, hundreds and sometimes even thousands. They are fast, acrobatic and playful, and are one of the species commonly found bow-riding off boats. They have also been observed working together to catch fish. These dolphins are often seen with other cetaceans, including northern right whale dolphins and Risso\'s dolphins.', fun_fact = 'These dolphins are known for their acrobatics, which include leaping, flipping, and somersaulting out of the water.', food = 'Pacific white-sided dolphins feed on a variety of prey, such as squid and small schooling fish (capelin, sardines, and herring)', ocean = ocean2, img= 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Pacific_white-sided_dolphins_%28Lagenorhynchus_obliquidens%29_NOAA.jpg' )
        animal3 = Animal(name='Leafy Sea Dragon', scientific_name = 'Phycodurus eques', lifespan= '7-10 years', about='It is found along the southern and western coasts of Australia. The name is derived from their appearance, with long leaf-like protrusions coming from all over the body. These protrusions are not used for propulsion; they serve only as camouflage. The leafy seadragon propels itself utilizing a pectoral fin on the ridge of its neck and a dorsal fin on its back closer to the tail end. These small fins are almost completely transparent and difficult to see as they undulate minutely to move the creature sedately through the water, completing the illusion of floating seaweed. Popularly known as "leafies", they are the marine emblem of the state of South Australia and a focus for local marine conservation.', fun_fact = 'As with its seahorse kin, a male leafy sea dragon carries its mate\'s eggs until the eggs hatch. Their leafy appendages, ability to change color to match their seaweed and seagrass habitats, and ability to sway like plants in the water current help protect them from predators.', food = 'The leafy sea dragon eats small shrimplike animals called mysids', ocean = ocean3, img= 'https://indianapublicmedia.org/images/amos-images/leafy_seadragon.jpg' )
        animal4 = Animal(name='Atlantic Salmon', scientific_name = 'Salmo salar', lifespan='5-8 years', about='Atlantic salmon, also known as the “King of Fish,” are anadromous, which means they live in both fresh and saltwater. They are considered an indicator species or a “canary in the coal mine.” This means that the health of the species is directly affected by its ecosystem health. When a river ecosystem is clean and well-connected, its salmon population is typically healthy and robust. When a river ecosystem is not clean or well-connected, its salmon population will usually decline.', fun_fact = 'Before spawning, Atlantic salmon change to a coppery red color with bright green heads.', food = 'Young and adult salmon eat a wide variety of prey, including: Fish: Capelin, Atlantic herring, sandlance, barracudina, lanternfish, alewife, rainbow smelt, mummichogs, flatfish, and small Atlantic mackerel. Crustaceans: Amphipods, euphausiids, and decapods. Cephalopods: Squid and octopus. Polychaete worms: Plankton like euphausiids.', ocean = ocean4 , img= 'https://e360.yale.edu/assets/site/_1500x1500_fit_center-center_80/Atlantic-Salmon_Getty-Small.jpg' )
        animal5 = Animal(name='Weddell Seal', scientific_name = 'Leptonychotes weddellii', lifespan='30 years', about='Adults in their prime weigh 400 to 450 kg (880 to 990 lbs.), with females being somewhat heavier than males, sometimes reaching over 500 kg (1,100 lbs.) Adult female weight fluctuates dramatically during the year with significant weight loss occurring after birth and during lactation.', fun_fact = 'Weddell seals are capable of diving up to 720 meters deep and staying underwater for up to 45 minutes. They dive deeper and longer during the day than at night. Also, Weddell seals are very vocal, and their calls can be heard from above the ice even when they are below.', food = 'Antarctic cod, Antarctic silverfish, myctophids, and nototheniids, Squid, octopus, Prawns, decapods, and Antarctic krill', ocean = ocean5, img= 'https://www.antarctica.gov.au/site/assets/files/45640/weddell-cuteness.1200x0.jpg' )
        animal6 = Animal(name='Atlantic spotted dolphin', scientific_name = 'Stenella frontalis', lifespan='10-20 years', about='Atlantic spotted dolphins are found in warm temperate and tropical waters of the Atlantic Ocean. They usually form groups of five to 50 individuals but sometimes travel in groups of up to 200. They are fast swimmers and often “surf” in the waves created by vessels. Young Atlantic spotted dolphins do not have spots. As a result, they can look like slender bottlenose dolphins. Their distinctive spotted pattern starts to appear all over their bodies as they get older.', fun_fact = 'Each Atlantic spotted dolphin has a unique spot pattern, which makes it possible to identify individual dolphins.', food = 'small fish, invertebrates, and cephalopods, such as squid and octopi', ocean = ocean1, img= 'https://www.thoughtco.com/thmb/uY4CWebloJkcJ5VkSPCvVCYsCKM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/atlantic-spotted-dolphin-and-calf-56b6c0983df78c0b135b9edd.jpg' )
        animal7 = Animal(name='Giant Pacific Octopus', scientific_name = 'Enteroctopus dofleini', lifespan='3-5 years', about='The Giant Pacific Octopus is one of the most elusive of all marine animals, reaching lengths of up to 16 feet and weighing in excess of 100 pounds. They are the largest known species of octopus, and they play an important part in the world\'s ecosystem.', fun_fact = 'Giant Pacific octopuses can change color in one-tenth of a second to match their surroundings. They have millions of pigment sacks in their skin cells that they can mix and match to create different colors.', food = 'Dungeness crabs are a favorite, but they also eat shrimp, scallops, and other crustaceans, Clams, squid, and other mollusks, birds, and sharks', ocean = ocean2, img= 'https://oceana.org/wp-content/uploads/sites/18/shutterstock_493454785.jpg' )
        animal8 = Animal(name='Adorned Wrasse', scientific_name = 'Halichoeres cosmetus', lifespan='10 years but mainly unknown', about='They live in reefs. In the wild, male adorned wrasses are usually found alone, while juvenile and female adorned wrasses form small groups.', fun_fact = 'These fish are sought after for aquariums', food = 'This wrasse naturally eats pyramidellid snails, fireworms, tubeworms, and flatworms', ocean = ocean3, img= 'https://seaunseen.com/wp-content/uploads/2017/08/MG_0260.jpg' )
        animal9 = Animal(name='Beluga Whale', scientific_name = 'Delphinapterus leucas', lifespan='35-50 years',  about='Belugas are extremely sociable mammals that live, hunt and migrate together in pods, ranging from a few individuals to hundreds of whales. Their bulbous forehead, called a "melon”, is flexible and capable of changing shape. This allows them to make different facial expressions. Belugas can produce a series of chirps, clicks, whistles and squeals, which give the beluga its other name, "the canary of the sea." ', fun_fact = 'Beluga whales typically swim at a speed of 2–6 miles per hour (mph), but can reach speeds of up to 14 mph in short bursts. Also, Beluga whales have flexible necks that allow them to move their heads in many directions, and flexible lips that can form smiles.', food = 'Salmon, herring, cod, smelt, flatfish, eulachon, capelin, lingcod, sculpin, Octopus, squid, shrimp, crab, clams, mussels, snails, and sandworms', ocean = ocean4 , img= 'https://cdn.i-scmp.com/sites/default/files/styles/1020x680/public/images/methode/2018/06/20/df74f43c-7395-11e8-aa4d-d2a0e82fc143_1280x720_162805.JPG?itok=U0cV59Xn' )
        animal10 = Animal(name='Emperor Penguin', scientific_name = 'Aptenodytes forsteri', lifespan='15-20 years', about='The emperor penguin is the tallest and heaviest of all living penguin species and is endemic to Antarctica. The male and female are similar in plumage and size, reaching 100 cm in length and weighing from 22 to 45 kg. They are excellent parents also.', fun_fact = 'Emperor penguins are the deepest diving birds, capable of diving over 800 feet and holding their breath for up to 22 minutes.', food = 'Emperor penguins primarily eat fish, krill, and squid', ocean = ocean5, img= 'https://images.amcnetworks.com/wonderstrucktv.com/wp-content/uploads/2020/05/1684502083649_1579732141068_1684511811918_mp4_video_1280x720_2500000_primary_audio_eng_5_1920x1080_1684860995621.jpg' )
        animal11 = Animal(name='Atlantic Petrel', scientific_name = 'Pterodroma incerta', lifespan='15 years', about='Atlantic petrels are endangered and its population is declining. The IUCN lists it as endangered due to its small breeding range and the high rate of chick predation by introduced house mice. Atlantic petrels spend most of their lives at sea, only coming ashore to nest and raise their fluffy chicks in cozy burrows.', fun_fact = 'The Atlantic petrel nests at night in burrows on cliffsides between 50 and 300 meters above sea level.', food = 'The Atlantic petrel\'s diet is mostly squid, but it also eats lanternfishes, crustaceans, and some fish.', ocean = ocean1, img= 'https://www.aabirdpix.com/Petrels/atlantic-petrel1.jpg' )
        animal12 = Animal(name='Hawaiian Monk Seal', scientific_name = 'Monachus schauinslandi', lifespan='25-30 years', about='The Hawaiian monk seal is one of the most endangered seal species in the world. Hawaiian monk seals are mainly threatened by entanglement in fishing gear, food availability, disease and predation, and although many protections are in place their numbers have continued to fall. There are only about 1,400 monk seals left. Hawaiian monk seals get their name from the folds of skin that resemble a monk\'s robe, and they\'re typically spotted alone or in small groups of seals. They can grow up to 7.5 feet long and weigh between 375 and 450 pounds. They can dive up to 1,500 feet. They also can accidentally kill or injure their partners during mating.', fun_fact = ' In Hawaiian, their name is \'īlio holo i ka uaua, which means "dog that runs in rough water', food = 'They eat fish, crustaceans, and cephalopods', ocean = ocean2, img= 'https://www.marinemammalcenter.org/storage/app/uploads/public/6ad/d70/1ad/thumb__1600_0_0_0_crop.jpg' )
        animal13 = Animal(name='Yellowtail Angelfish', scientific_name = 'Apolemichthys xanthurus', lifespan='8-15 years', about='The yellowtail angelfish has many common names including cream angelfish, smoke angelfish, and yellowtail black angelfish. It is hermaphroditic, and there are no distinguishing features which differentiate males from females. Hermaphroditic means having both male and female reproductive organs, structures, or tissue.', fun_fact = 'The name "angelfish" comes from the fish\'s shape, which resembles an angel\'s head, wings, and dress when viewed from the side.', food = 'Yellowtail angelfish are omnivores that eat sponges, tunicates, and crustaceans.', ocean = ocean3, img= 'https://cdn2.reefapp.net/medium/apolemichthys-xanthurus-992aa1e2da6d4963ac0ccfcfd6f58dad.jpg' )
        animal14 = Animal(name='Arctic Cod', scientific_name = 'Boreogadus saida', lifespan='7-8 years', about='Arctic cod also known as the polar cod. Arctic cod can be distinguished from their warm-water cousins by their elongated body and protruding lower jaw, as well as their v-shaped tail. They are considerably smaller than other cod, growing to only about 30 centimetres in length. They also tend to be smaller the farther south they are found. They have brown backs spotted with black, silvery sides and bellies, and pale lateral lines running along each side of the body from head to tail. Their scales are very small.', fun_fact = 'Arctic cod produce glycoproteins in their blood that act as antifreeze, allowing them to survive in freezing waters.', food = 'Arctic cod eat krill and plankton.', ocean = ocean4, img= 'https://nofima.com/wp-content/uploads/sites/2/2021/06/crisp_topp.jpg' )
        animal15 = Animal(name='Snowy Albatross', scientific_name = 'Diomedea exulans', lifespan='80 years or more', about='The snowy albatross, also known as the white-winged albatross, wandering albatross, or goonie, is a large seabird.  Snowy albatrosses are highly pelagic and spend most of their time wandering the Southern Ocean, only coming to land to breed every two years. Some snowy albatrosses have been known to circumnavigate the Southern Ocean three times in a year, covering more than 75,000 miles (120,000 kilometers).', fun_fact = 'It is the largest of twenty-one albatross species and has the greatest known wingspan of any living bird, reaching up to 3.6 meters (12 feet). It is one of the most studied species of bird.', food = 'Fish, cephalopods, crustaceans, jellyfish, carrion, bait', ocean = ocean5, img= 'https://cdn.download.ams.birds.cornell.edu/api/v1/asset/204864691/640' )
        animal16 = Animal(name='North Atlantic right whale', scientific_name = 'Eubalaena glacialis', lifespan='70 years reduced because human-caused mortality', about='The North Atlantic right whale is one of the world\'s most endangered large whale species. There are about only less than 360 left. By the early 1890s, commercial whalers had hunted North Atlantic right whales to the brink of extinction. (They got their name from being the "right" whales to hunt because they floated when they were killed.) These white, knobby patches on their heads are unique to each whale and are caused by whale lice. Scientists use these patterns to identify individual whales and track their population health.', fun_fact = 'Scientists have found they can eat between 2,200 and 5,500 pounds of food every day!', food = 'zooplankton, including copepods, krill, and other small crustaceans', ocean = ocean1, img= 'https://i.natgeofe.com/n/e1d09939-2129-43e0-ae93-dd55edc9b00f/01-north-atlantic-right-whale-nationalgeographic_1214878_16x9.jpg' )
        animal17 = Animal(name='Sea Otter', scientific_name = 'Enhydra lutris', lifespan='Female: 15-20 years, Male: 10-15 years', about=' Sea otters have webbed feet, water-repellent fur to keep them dry and warm, and nostrils and ears that close in the water. Sea otters often float at the water\'s surface, lying on their backs. They sleep this way, often gathered in groups. Otters sometimes float in forests of kelp, or giant seaweed, in which they entangle themselves to provide anchorage in the swirling sea. Sea otters have teeth that are twice as strong as human teeth, which helps them break open the shells of their food.', fun_fact = 'Sea otters have the densest fur of any animal in the world, with up to one million hairs per square inch. This fur traps air to insulate them from the cold Pacific Ocean waters.', food = 'marine invertebrates', ocean = ocean2, img= 'https://www.mmc.gov/wp-content/uploads/Sea-otter2004-by-Ryan-Wolt-MA-043219-21.jpg' )
        animal18 = Animal(name='Box jellyfish Carybdea wayamba ', scientific_name = 'Carybdea wayamba sp. nov. ( Cnidaria: Scyphozoa: Cubomedusae: Carybdeidae', lifespan='Not known', about='This species of jellyfish was just discovered in 2020, It is a new species of Box jellyfish. ', fun_fact = 'Box jellyfish have 24 eyes spread across their bell, giving them 360-degree vision. Some of their eyes are more sophisticated than others, with lenses, corneas, irises, and retinas', food = 'Shrinp and krill', ocean = ocean3, img= 'https://imgs.mongabay.com/wp-content/uploads/sites/20/2022/09/21161542/4-A-hazardous-box-jellyfish-from-Sri-Lanka-1-768x450.jpg' )
        animal19 = Animal(name='Polar Bear', scientific_name = 'Ursus maritimus', lifespan='25-30 years', about='The polar bear is the largest bear in the world and the Arctic\'s top predator. The polar bear\'s Latin name, Ursus maritimus, means "sea bear." Polar bears spend over 50 percent of their time hunting for food. A polar bear might catch only one or two out of 10 seals it hunts.  The largest males can weigh in excess of 1700 lbs, but the average is 600–1200 lbs and 8–10 feet in length. Adult females weigh 400–700 lbs. They also have black skin under their white fur', fun_fact = ' Polar bears spend most of their lives alone, except when feeding on a whale carcass, raising cubs, or mating.', food = 'Seals, carcasses, birds, fish, and vegatation', ocean = ocean4, img= 'https://bloximages.newyork1.vip.townnews.com/valpotorch.com/content/tncms/assets/v3/editorial/3/4b/34b39260-c783-11ec-9097-f3d860fdf9c7/626b82e91b1c1.image.jpg?resize=1200%2C755' )
        animal20 = Animal(name='Antarctic Fur Seals', scientific_name = 'Arctocephalus gazella', lifespan='Female: 25 years, Male: 15 years', about='Antarctic Fur Seals were almost hunted to extinction. They weigh from 90-215 kg, males being larger. Male Antarctic fur seals are much larger than females, with males weighing up to four times more than females. Adult males are dark brown in colour. Females and juveniles tend to be paler, almost grey with lighter undersides. Colour patterns are highly variable, and scientists reported that some hybridization between Subantarctic and Antarctic fur seals has occurred.', fun_fact = 'A small percentage of Antarctic fur seals are born with a rare genetic mutation that causes them to have white or blonde fur. Also, Antarctic fur seals can move around on all fours and travel up to 12.5 miles per hour on land.', food = ' Krill, squid, fish, penguins.', ocean = ocean5, img= 'https://www.antarctica.gov.au/site/assets/files/45617/rs34085_nh_furseal_4.1920x768.jpg' )


        user1 = User(username = 'achippy', _password_hash = '3564gfbd')
        user2 = User(username = 'budweiser', _password_hash = 'mdnsjs7')

        favorite1 = Favorite(user_id=1, animal_id=1)
        favorite2 = Favorite(user_id=1, animal_id=6)
        favorite3 = Favorite(user_id=2, animal_id=19)
        favorite4 = Favorite(user_id=2, animal_id=12)


        db.session.add_all([
            ocean1, ocean2, ocean3, ocean4, ocean5,
            animal1, animal2, animal3, animal4, animal5, animal6, animal7, animal8, animal9, animal10,
            animal11, animal12, animal13, animal14, animal15, animal16, animal17, animal18, animal19, animal20,
            user1, user2,
            favorite1, favorite2, favorite3, favorite4
        ])

        db.session.commit()

        print("Seeding complete!")

    



