"""initial migration

Revision ID: 557e01b753d4
Revises: 
Create Date: 2024-09-23 11:03:24.685899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557e01b753d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oceans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avg_depth', sa.String(), nullable=True),
    sa.Column('deepest_point', sa.String(), nullable=True),
    sa.Column('surface_area', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('ofun_fact', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('map', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('lifespan', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('fun_fact', sa.String(), nullable=True),
    sa.Column('food', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('ocean_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ocean_id'], ['oceans.id'], name=op.f('fk_animals_ocean_id_oceans')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_favorites_animal_id_animals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('animals')
    op.drop_table('users')
    op.drop_table('oceans')
    # ### end Alembic commands ###
